apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
status:
  conditions:
    - type: NamesAccepted
      status: 'True'
      lastTransitionTime: '2021-11-18T06:24:03Z'
      reason: NoConflicts
      message: no conflicts found
    - type: Established
      status: 'True'
      lastTransitionTime: '2021-11-18T06:24:03Z'
      reason: InitialNamesAccepted
      message: the initial names have been accepted
  acceptedNames:
    plural: sealedsecrets
    singular: sealedsecret
    kind: SealedSecret
    listKind: SealedSecretList
  storedVersions:
    - v1alpha1
spec:
  group: bitnami.com
  names:
    plural: sealedsecrets
    singular: sealedsecret
    kind: SealedSecret
    listKind: SealedSecretList
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
  conversion:
    strategy: None
