#Your build pipeline references a secret variable named 'NETLIFY_AUTH_TOKEN'. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

variables:
  NETLIFY_SITE_ID: 'f3844224-cd13-4870-833e-3a10814d8861'

jobs:
- job: build
  timeoutInMinutes: 10
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core sdk'
    inputs:
      version: '3.0.100-rc1-014190'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      arguments: ' -c Release'
      workingDirectory: src/KubeUI

  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
      command: publish
      publishWebProjects: false
      arguments: ' -c Release -o $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
      modifyOutputPath: false
      workingDirectory: src/KubeUI

  - task: PowerShell@2
    displayName: 'Install Netlify-CLI'
    inputs:
      targetType: 'inline'
      script: |
        npm install netlify-cli -g

  - task: PowerShell@2
    displayName: 'Deploy to Netlify-CI'
    inputs:
      targetType: 'inline'
      script: |
        $env:NETLIFY_AUTH_TOKEN = "$(NETLIFY_AUTH_TOKEN)";
        $env:NETLIFY_SITE_ID = "$(NETLIFY_SITE_ID)";
        $output = (netlify deploy --json -d $(Build.ArtifactStagingDirectory)/KubeUI/dist/) | Out-String;
        $url = $(ConvertFrom-Json $output).deploy_url;
        Write-Host $url;
        Set-Content -Path "src/KubeUI.Tests/BrowserTestsAddress.config" -Value $url;

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      arguments: ' -c Release'
      workingDirectory: src/KubeUI.Tests

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: binaries'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/KubeUI/dist/'
      ArtifactName: binaries
