<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>

    <EnableAvaloniaXamlCompilation>false</EnableAvaloniaXamlCompilation>

    <WarningsAsErrors>$(WarningsAsErrors);CA1001</WarningsAsErrors>

    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --config-file $(MSBuildThisFileDirectory)testconfig.json</TestingPlatformCommandLineArguments>

    <!-- Disable Avalonia.BuildServices' AvaloniaStats task for all projects.
         Due to build errors, System.UnauthorizedAccessException: Access to the path 'C:\Users\username\AppData\Local\AvaloniaUI\BuildServices\buildtasks.log' is denied.
    -->
    <UsedAvaloniaProducts></UsedAvaloniaProducts>
  </PropertyGroup>
</Project>
