services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    pull_policy: always
    container_name: aspire-dashboard
    ports:
      - "18888:18888"
      - "4317:18889"
      - "4318:18890"
    restart: unless-stopped