//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KubeUI.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KubeUI.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Ivan Josipovic.
        /// </summary>
        public static string AboutView_Header {
            get {
                return ResourceManager.GetString("AboutView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Version.
        /// </summary>
        public static string AboutView_Version_FallbackValue {
            get {
                return ResourceManager.GetString("AboutView_Version_FallbackValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AboutView_Version_StringFormat {
            get {
                return ResourceManager.GetString("AboutView_Version_StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Action_Copy {
            get {
                return ResourceManager.GetString("Action_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Action_Cut {
            get {
                return ResourceManager.GetString("Action_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Action_Paste {
            get {
                return ResourceManager.GetString("Action_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Action_Redo {
            get {
                return ResourceManager.GetString("Action_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Action_Undo {
            get {
                return ResourceManager.GetString("Action_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have the necessary permissions to list or watch namespaces. Please enter the names of the namespaces this account should have access to in the Settings window, and then reconnect.
        /// </summary>
        public static string Cluster_Missing_Namespace_Permission_Content {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Cluster_Missing_Namespace_Permission_Primary {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Cluster_Missing_Namespace_Permission_Title {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the cluster.
        /// </summary>
        public static string ClusterErrorView_Header {
            get {
                return ResourceManager.GetString("ClusterErrorView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Error.
        /// </summary>
        public static string ClusterErrorViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterErrorViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cluster: {0}.
        /// </summary>
        public static string ClusterListViewModel_Delete_Content {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ClusterListViewModel_Delete_Primary {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ClusterListViewModel_Delete_Secondary {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ClusterListViewModel_Delete_Title {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        public static string ClusterListViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Settings.
        /// </summary>
        public static string ClusterSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterSettingsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        public static string ClusterViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to KubeUI!.
        /// </summary>
        public static string HomeView_Header {
            get {
                return ResourceManager.GetString("HomeView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeViewModel_Title {
            get {
                return ResourceManager.GetString("HomeViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainView_Menu_File {
            get {
                return ResourceManager.GetString("MainView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        public static string MainView_Menu_File_Clusters {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MainView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MainView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainView_Menu_Help {
            get {
                return ResourceManager.GetString("MainView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MainView_Menu_Help_About {
            get {
                return ResourceManager.GetString("MainView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MainView_Menu_Window {
            get {
                return ResourceManager.GetString("MainView_Menu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Layout.
        /// </summary>
        public static string MainView_Menu_Window_ResetLayout {
            get {
                return ResourceManager.GetString("MainView_Menu_Window_ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Theme.
        /// </summary>
        public static string MainView_Menu_Window_SwitchTheme {
            get {
                return ResourceManager.GetString("MainView_Menu_Window_SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update is available. Update and restart now?.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Content {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Primary {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Secondary {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Available.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Updating_Content {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Updating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Updating_Title {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Updating_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Yamls in Folder.
        /// </summary>
        public static string NavigationViewModel_LoadFolder {
            get {
                return ResourceManager.GetString("NavigationViewModel_LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Yaml.
        /// </summary>
        public static string NavigationViewModel_LoadYaml {
            get {
                return ResourceManager.GetString("NavigationViewModel_LoadYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string NavigationViewModel_Title {
            get {
                return ResourceManager.GetString("NavigationViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pod Console.
        /// </summary>
        public static string PodConsoleViewModel_Title {
            get {
                return ResourceManager.GetString("PodConsoleViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-scroll to bottom.
        /// </summary>
        public static string PodLogsView_AutoScrollToBottom {
            get {
                return ResourceManager.GetString("PodLogsView_AutoScrollToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last container.
        /// </summary>
        public static string PodLogsView_Previous {
            get {
                return ResourceManager.GetString("PodLogsView_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        public static string PodLogsView_Timestamps {
            get {
                return ResourceManager.GetString("PodLogsView_Timestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string PodLogsView_WordWrap {
            get {
                return ResourceManager.GetString("PodLogsView_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pod Logs.
        /// </summary>
        public static string PodLogsViewModel_Title {
            get {
                return ResourceManager.GetString("PodLogsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the Port Forward for {0}/{1}:{2}?
        ///Are you sure?.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Content {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Primary {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Secondary {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Title {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Forwarding.
        /// </summary>
        public static string PortForwarderListViewModel_Title {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Resource.
        /// </summary>
        public static string ResourceListView_NewResource {
            get {
                return ResourceManager.GetString("ResourceListView_NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Namespace(s).
        /// </summary>
        public static string ResourceListView_SelectNamespace {
            get {
                return ResourceManager.GetString("ResourceListView_SelectNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordon Nodes {0}.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete {0} items.
        ///Are you sure?.
        /// </summary>
        public static string ResourceListViewModel_Delete_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_Delete_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_Delete_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_Delete_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain Nodes {0}.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} was forwarded to {1}..
        /// </summary>
        public static string ResourceListViewModel_PortForward_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string ResourceListViewModel_PortForward_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ResourceListViewModel_PortForward_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Forward.
        /// </summary>
        public static string ResourceListViewModel_PortForward_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will restart {0}.
        ///Are you sure?.
        /// </summary>
        public static string ResourceListViewModel_Restart_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_Restart_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_Restart_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Workload?.
        /// </summary>
        public static string ResourceListViewModel_Restart_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnCordon Nodes {0}.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ResourcePropertiesViewModel_Title {
            get {
                return ResourceManager.GetString("ResourcePropertiesViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string ResourceYamlView_WordWrap {
            get {
                return ResourceManager.GetString("ResourceYamlView_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ResourceYamlViewer_Cancel {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ResourceYamlViewer_Edit {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide noisy fields.
        /// </summary>
        public static string ResourceYamlViewer_HideNoisyFields {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_HideNoisyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ResourceYamlViewer_Save {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ResourceYamlViewer_Undo {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaml.
        /// </summary>
        public static string ResourceYamlViewModel_Title {
            get {
                return ResourceManager.GetString("ResourceYamlViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string VisualizationViewModel_Title {
            get {
                return ResourceManager.GetString("VisualizationViewModel_Title", resourceCulture);
            }
        }
    }
}
