<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.4" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KubeUI.Kubernetes\KubeUI.Kubernetes.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KubeUI.Kubernetes.Tests" />
    <InternalsVisibleTo Include="KubeUI.Benchmarks" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="KubeUI.Kubernetes" />
  </ItemGroup>

</Project>
