apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bot
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: bot
        - name: POSTGRES_PASSWORD
          value: password123
        - name: POSTGRES_USER
          value: admin_sql
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: index.docker.io/postgres:11.3-alpine
        name: postgres
        args: ["-c", "max_connections=1000"]
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "2000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
      restartPolicy: Always
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresdata