//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KubeUI.Avalonia.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KubeUI.Avalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string AboutView_Contact {
            get {
                return ResourceManager.GetString("AboutView_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Ivan Josipovic.
        /// </summary>
        public static string AboutView_CreatedBy {
            get {
                return ResourceManager.GetString("AboutView_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Version.
        /// </summary>
        public static string AboutView_Version_FallbackValue {
            get {
                return ResourceManager.GetString("AboutView_Version_FallbackValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AboutView_Version_StringFormat {
            get {
                return ResourceManager.GetString("AboutView_Version_StringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        public static string AboutView_Website {
            get {
                return ResourceManager.GetString("AboutView_Website", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to admin@KubeUI.com.
        /// </summary>
        public static string AboutView_ContactEmailContent {
            get {
                return ResourceManager.GetString("AboutView_ContactEmailContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mailto:admin@KubeUI.com.
        /// </summary>
        public static string AboutView_ContactEmailUri {
            get {
                return ResourceManager.GetString("AboutView_ContactEmailUri", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KubeUI.com.
        /// </summary>
        public static string AboutView_WebsiteContent {
            get {
                return ResourceManager.GetString("AboutView_WebsiteContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to https://KubeUI.com.
        /// </summary>
        public static string AboutView_WebsiteUri {
            get {
                return ResourceManager.GetString("AboutView_WebsiteUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Action_Copy {
            get {
                return ResourceManager.GetString("Action_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Action_Cut {
            get {
                return ResourceManager.GetString("Action_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Action_Paste {
            get {
                return ResourceManager.GetString("Action_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Action_Redo {
            get {
                return ResourceManager.GetString("Action_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Action_Undo {
            get {
                return ResourceManager.GetString("Action_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have the necessary permissions to list or watch namespaces. Please enter the names of the namespaces this account should have access to in the Settings window, and then reconnect.
        /// </summary>
        public static string Cluster_Missing_Namespace_Permission_Content {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Cluster_Missing_Namespace_Permission_Primary {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Cluster_Missing_Namespace_Permission_Title {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the cluster.
        /// </summary>
        public static string ClusterErrorView_Header {
            get {
                return ResourceManager.GetString("ClusterErrorView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Error.
        /// </summary>
        public static string ClusterErrorViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterErrorViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Cluster from Kube Config: {0}.
        /// </summary>
        public static string ClusterListViewModel_Delete_Content {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ClusterListViewModel_Delete_Primary {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ClusterListViewModel_Delete_Secondary {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ClusterListViewModel_Delete_Title {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        public static string ClusterListViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ClusterListView_Delete {
            get {
                return ResourceManager.GetString("ClusterListView_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KubeConfig.
        /// </summary>
        public static string ClusterListView_KubeConfig {
            get {
                return ResourceManager.GetString("ClusterListView_KubeConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClusterListView_Name {
            get {
                return ResourceManager.GetString("ClusterListView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Settings.
        /// </summary>
        public static string ClusterSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterSettingsViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ClusterSettingsView_Add {
            get {
                return ResourceManager.GetString("ClusterSettingsView_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Settings.
        /// </summary>
        public static string ClusterSettingsView_TitleFormat {
            get {
                return ResourceManager.GetString("ClusterSettingsView_TitleFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manually specified namespaces.
        /// </summary>
        public static string ClusterSettingsView_ManualNamespacesTooltip {
            get {
                return ResourceManager.GetString("ClusterSettingsView_ManualNamespacesTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Namespaces (Restart Required).
        /// </summary>
        public static string ClusterSettingsView_NamespacesLabel {
            get {
                return ResourceManager.GetString("ClusterSettingsView_NamespacesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ClusterSettingsView_Remove {
            get {
                return ResourceManager.GetString("ClusterSettingsView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        public static string ClusterViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string ClusterView_Cpu {
            get {
                return ResourceManager.GetString("ClusterView_Cpu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Allocatable.
        /// </summary>
        public static string ClusterView_CpuAllocatable {
            get {
                return ResourceManager.GetString("ClusterView_CpuAllocatable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Capacity.
        /// </summary>
        public static string ClusterView_CpuCapacity {
            get {
                return ResourceManager.GetString("ClusterView_CpuCapacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Limits.
        /// </summary>
        public static string ClusterView_CpuLimits {
            get {
                return ResourceManager.GetString("ClusterView_CpuLimits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Requests.
        /// </summary>
        public static string ClusterView_CpuRequests {
            get {
                return ResourceManager.GetString("ClusterView_CpuRequests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Usage.
        /// </summary>
        public static string ClusterView_CpuUsage {
            get {
                return ResourceManager.GetString("ClusterView_CpuUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string ClusterView_Events {
            get {
                return ResourceManager.GetString("ClusterView_Events", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string ClusterView_Memory {
            get {
                return ResourceManager.GetString("ClusterView_Memory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Allocatable.
        /// </summary>
        public static string ClusterView_MemoryAllocatable {
            get {
                return ResourceManager.GetString("ClusterView_MemoryAllocatable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Capacity.
        /// </summary>
        public static string ClusterView_MemoryCapacity {
            get {
                return ResourceManager.GetString("ClusterView_MemoryCapacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Limits.
        /// </summary>
        public static string ClusterView_MemoryLimits {
            get {
                return ResourceManager.GetString("ClusterView_MemoryLimits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Requests.
        /// </summary>
        public static string ClusterView_MemoryRequests {
            get {
                return ResourceManager.GetString("ClusterView_MemoryRequests", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        public static string ClusterView_MemoryUsage {
            get {
                return ResourceManager.GetString("ClusterView_MemoryUsage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pods.
        /// </summary>
        public static string ClusterView_Pods {
            get {
                return ResourceManager.GetString("ClusterView_Pods", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string ClusterView_PodsCapacity {
            get {
                return ResourceManager.GetString("ClusterView_PodsCapacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string ClusterView_PodsCount {
            get {
                return ResourceManager.GetString("ClusterView_PodsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to KubeUI!.
        /// </summary>
        public static string HomeView_Header {
            get {
                return ResourceManager.GetString("HomeView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeViewModel_Title {
            get {
                return ResourceManager.GetString("HomeViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainView_Menu_File {
            get {
                return ResourceManager.GetString("MainView_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        public static string MainView_Menu_File_Clusters {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MainView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load Kube Config.
        /// </summary>
        public static string MainView_Menu_File_LoadKubeConfig {
            get {
                return ResourceManager.GetString("MainView_Menu_File_LoadKubeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Kube Config.
        /// </summary>
        public static string MainView_Menu_File_LoadKubeConfig_Open {
            get {
                return ResourceManager.GetString("MainView_Menu_File_LoadKubeConfig_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings.
        /// </summary>
        public static string MainView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MainView_Menu_Help {
            get {
                return ResourceManager.GetString("MainView_Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MainView_Menu_Help_About {
            get {
                return ResourceManager.GetString("MainView_Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string MainView_Menu_Window {
            get {
                return ResourceManager.GetString("MainView_Menu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Layout.
        /// </summary>
        public static string MainView_Menu_Window_ResetLayout {
            get {
                return ResourceManager.GetString("MainView_Menu_Window_ResetLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Theme.
        /// </summary>
        public static string MainView_Menu_Window_SwitchTheme {
            get {
                return ResourceManager.GetString("MainView_Menu_Window_SwitchTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update and restart now?.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Content {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Primary {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Secondary {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Available.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Updating_Content {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Updating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        public static string MainViewModel_CheckForUpdates_Updating_Title {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Updating_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Yamls in Folder.
        /// </summary>
        public static string NavigationViewModel_LoadFolder {
            get {
                return ResourceManager.GetString("NavigationViewModel_LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Yaml.
        /// </summary>
        public static string NavigationViewModel_LoadYaml {
            get {
                return ResourceManager.GetString("NavigationViewModel_LoadYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string NavigationViewModel_Title {
            get {
                return ResourceManager.GetString("NavigationViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click to Connect.
        /// </summary>
        public static string NavigationView_ToolTip_ClickToConnect {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_ClickToConnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string NavigationView_ToolTip_Connected {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_Connected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string NavigationView_ToolTip_Connecting {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_Connecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Errored.
        /// </summary>
        public static string NavigationView_ToolTip_Errored {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_Errored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string NavigationView_ContextMenu_Connect {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Connect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string NavigationView_ContextMenu_Disconnect {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavigationView_ContextMenu_Settings {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NavigationView_ContextMenu_Open {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open New Tab.
        /// </summary>
        public static string NavigationView_ContextMenu_OpenNewTab {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_OpenNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pod Console.
        /// </summary>
        public static string PodConsoleViewModel_Title {
            get {
                return ResourceManager.GetString("PodConsoleViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        public static string PodContainerCell_NameFormat {
            get {
                return ResourceManager.GetString("PodContainerCell_NameFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Init-Ready.
        /// </summary>
        public static string PodContainerCell_InitReady {
            get {
                return ResourceManager.GetString("PodContainerCell_InitReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Init-Starting.
        /// </summary>
        public static string PodContainerCell_InitStarting {
            get {
                return ResourceManager.GetString("PodContainerCell_InitStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Init-Stopped.
        /// </summary>
        public static string PodContainerCell_InitStopped {
            get {
                return ResourceManager.GetString("PodContainerCell_InitStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string PodContainerCell_Ready {
            get {
                return ResourceManager.GetString("PodContainerCell_Ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string PodContainerCell_Starting {
            get {
                return ResourceManager.GetString("PodContainerCell_Starting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string PodContainerCell_Stopped {
            get {
                return ResourceManager.GetString("PodContainerCell_Stopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pod:.
        /// </summary>
        public static string PodLogsView_PodLabel {
            get {
                return ResourceManager.GetString("PodLogsView_PodLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string PodStatusCell_Running {
            get {
                return ResourceManager.GetString("PodStatusCell_Running", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PodCompleted.
        /// </summary>
        public static string PodStatusCell_PodCompleted {
            get {
                return ResourceManager.GetString("PodStatusCell_PodCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminating.
        /// </summary>
        public static string PodStatusCell_Terminating {
            get {
                return ResourceManager.GetString("PodStatusCell_Terminating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string PodStatusCell_Unknown {
            get {
                return ResourceManager.GetString("PodStatusCell_Unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ControlledBy.
        /// </summary>
        public static string PodPropertiesView_ControlledBy {
            get {
                return ResourceManager.GetString("PodPropertiesView_ControlledBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string PodPropertiesView_Image {
            get {
                return ResourceManager.GetString("PodPropertiesView_Image", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        public static string PodPropertiesView_Containers {
            get {
                return ResourceManager.GetString("PodPropertiesView_Containers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Init Containers.
        /// </summary>
        public static string PodPropertiesView_InitContainers {
            get {
                return ResourceManager.GetString("PodPropertiesView_InitContainers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string PodPropertiesView_Node {
            get {
                return ResourceManager.GetString("PodPropertiesView_Node", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PodPropertiesView_Name {
            get {
                return ResourceManager.GetString("PodPropertiesView_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pod IP.
        /// </summary>
        public static string PodPropertiesView_PodIp {
            get {
                return ResourceManager.GetString("PodPropertiesView_PodIp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pull Policy.
        /// </summary>
        public static string PodPropertiesView_PullPolicy {
            get {
                return ResourceManager.GetString("PodPropertiesView_PullPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PodPropertiesView_Status {
            get {
                return ResourceManager.GetString("PodPropertiesView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-scroll to bottom.
        /// </summary>
        public static string PodLogsView_AutoScrollToBottom {
            get {
                return ResourceManager.GetString("PodLogsView_AutoScrollToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Logs.
        /// </summary>
        public static string PodLogsView_Clear {
            get {
                return ResourceManager.GetString("PodLogsView_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last container.
        /// </summary>
        public static string PodLogsView_Previous {
            get {
                return ResourceManager.GetString("PodLogsView_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show timestamps.
        /// </summary>
        public static string PodLogsView_Timestamps {
            get {
                return ResourceManager.GetString("PodLogsView_Timestamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string PodLogsView_WordWrap {
            get {
                return ResourceManager.GetString("PodLogsView_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pod Logs.
        /// </summary>
        public static string PodLogsViewModel_Title {
            get {
                return ResourceManager.GetString("PodLogsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the Port Forward for {0}/{1}:{2}?
        ///Are you sure?.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Content {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Primary {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Secondary {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string PortForwarderListViewModel_Remove_Title {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Forwarding.
        /// </summary>
        public static string PortForwarderListViewModel_Title {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Resource.
        /// </summary>
        public static string ResourceListView_NewResource {
            get {
                return ResourceManager.GetString("ResourceListView_NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked namespace selection.
        /// </summary>
        public static string ResourceListView_NamespaceLink {
            get {
                return ResourceManager.GetString("ResourceListView_NamespaceLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        public static string ResourceListView_ItemsFormat {
            get {
                return ResourceManager.GetString("ResourceListView_ItemsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ResourceListView_SearchWatermark {
            get {
                return ResourceManager.GetString("ResourceListView_SearchWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Items: {0}.
        /// </summary>
        public static string VisualizationView_ItemsFormat {
            get {
                return ResourceManager.GetString("VisualizationView_ItemsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide noisy resources like inactive Replica Sets.
        /// </summary>
        public static string VisualizationView_HideNoiseTooltip {
            get {
                return ResourceManager.GetString("VisualizationView_HideNoiseTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string VisualizationView_Properties {
            get {
                return ResourceManager.GetString("VisualizationView_Properties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Yaml.
        /// </summary>
        public static string VisualizationView_ViewYaml {
            get {
                return ResourceManager.GetString("VisualizationView_ViewYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Namespace(s).
        /// </summary>
        public static string ResourceListView_SelectNamespace {
            get {
                return ResourceManager.GetString("ResourceListView_SelectNamespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ResourceListViewModel_Filter_Apply {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Apply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string ResourceListViewModel_Filter_Any {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Any", resourceCulture);
            }
        }

        /// <summary>
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string ResourceListViewModel_Filter_And {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_And", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        public static string ResourceListViewModel_Filter_Between {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Between", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ResourceListViewModel_Filter_Clear {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string ResourceListViewModel_Filter_Contains {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Contains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string ResourceListViewModel_Filter_EndsWith {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_EndsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string ResourceListViewModel_Filter_Equals {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Equals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string ResourceListViewModel_Filter_GreaterThan {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_GreaterThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal.
        /// </summary>
        public static string ResourceListViewModel_Filter_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_GreaterThanOrEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        public static string ResourceListViewModel_Filter_LessThan {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_LessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Less than or equal.
        /// </summary>
        public static string ResourceListViewModel_Filter_LessThanOrEqual {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_LessThanOrEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Newer than.
        /// </summary>
        public static string ResourceListViewModel_Filter_NewerThan {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_NewerThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Older than.
        /// </summary>
        public static string ResourceListViewModel_Filter_OlderThan {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_OlderThan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string ResourceListViewModel_Filter_StartsWith {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_StartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ResourceListViewModel_Filter_Value {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string ResourceListViewModel_Filter_Minutes {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Minutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string ResourceListViewModel_Filter_Hours {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string ResourceListViewModel_Filter_Days {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string ResourceListViewModel_Filter_Months {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Filter_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordon Nodes {0}.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_CordonNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete {0} items.
        ///Are you sure?.
        /// </summary>
        public static string ResourceListViewModel_Delete_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_Delete_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_Delete_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_Delete_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drain Nodes {0}.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_DrainNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port {0} was forwarded to {1}..
        /// </summary>
        public static string ResourceListViewModel_PortForward_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string ResourceListViewModel_PortForward_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ResourceListViewModel_PortForward_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Forward.
        /// </summary>
        public static string ResourceListViewModel_PortForward_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will restart {0}.
        ///Are you sure?.
        /// </summary>
        public static string ResourceListViewModel_Restart_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_Restart_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_Restart_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Workload?.
        /// </summary>
        public static string ResourceListViewModel_Restart_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnCordon Nodes {0}.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string ResourceListViewModel_UnCordonNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string ResourcePropertiesViewModel_Title {
            get {
                return ResourceManager.GetString("ResourcePropertiesViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string ResourcePropertiesView_Created {
            get {
                return ResourceManager.GetString("ResourcePropertiesView_Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ResourcePropertiesView_Name {
            get {
                return ResourceManager.GetString("ResourcePropertiesView_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string ResourcePropertiesView_Namespace {
            get {
                return ResourceManager.GetString("ResourcePropertiesView_Namespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string SecretPropertiesView_Data {
            get {
                return ResourceManager.GetString("SecretPropertiesView_Data", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        public static string SecretPropertiesView_Certificates {
            get {
                return ResourceManager.GetString("SecretPropertiesView_Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Wrap.
        /// </summary>
        public static string ResourceYamlView_WordWrap {
            get {
                return ResourceManager.GetString("ResourceYamlView_WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ResourceYamlViewer_Cancel {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Run.
        /// </summary>
        public static string ResourceYamlViewer_DryRun {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry run failed.
        /// </summary>
        public static string ResourceYamlViewer_DryRunFailed {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry run succeeded.
        /// </summary>
        public static string ResourceYamlViewer_DryRunSucceeded {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRunSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server accepted the manifest using dry-run..
        /// </summary>
        public static string ResourceYamlViewer_DryRunSucceededMessage {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRunSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string ResourceYamlViewer_SaveFailed {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succeeded.
        /// </summary>
        public static string ResourceYamlViewer_SaveSucceeded {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_SaveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest was saved successfully..
        /// </summary>
        public static string ResourceYamlViewer_SaveSucceededMessage {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_SaveSucceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ResourceYamlViewer_Edit {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide noisy fields.
        /// </summary>
        public static string ResourceYamlViewer_HideNoisyFields {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_HideNoisyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ResourceYamlViewer_Save {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        public static string ResourceYamlViewer_ValidationFailed {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string ResourceYamlViewer_Undo {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaml.
        /// </summary>
        public static string ResourceYamlViewModel_Title {
            get {
                return ResourceManager.GetString("ResourceYamlViewModel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsView_Theme {
            get {
                return ResourceManager.GetString("SettingsView_Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsView_Theme_Default {
            get {
                return ResourceManager.GetString("SettingsView_Theme_Default", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsView_Theme_Dark {
            get {
                return ResourceManager.GetString("SettingsView_Theme_Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Local File Logging (Restart Required).
        /// </summary>
        public static string SettingsView_Logging_Label {
            get {
                return ResourceManager.GetString("SettingsView_Logging_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KubeUI logs to the local file system in the &lt;User Profile&gt;/.kubeui/app.log.
        /// </summary>
        public static string SettingsView_Logging_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_Logging_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable Telemetry (Restart Required).
        /// </summary>
        public static string SettingsView_Telemetry_Label {
            get {
                return ResourceManager.GetString("SettingsView_Telemetry_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KubeUI gathers telemetry data to help the team improve the product..
        /// </summary>
        public static string SettingsView_Telemetry_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_Telemetry_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pre Release Channel.
        /// </summary>
        public static string SettingsView_PreRelease_Label {
            get {
                return ResourceManager.GetString("SettingsView_PreRelease_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allows updates to pre-release versions of KubeUI.
        /// </summary>
        public static string SettingsView_PreRelease_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_PreRelease_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string SettingsView_FontSize_Label {
            get {
                return ResourceManager.GetString("SettingsView_FontSize_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string SettingsView_FontSize_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_FontSize_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console/Logs/Yaml Font Size.
        /// </summary>
        public static string SettingsView_ConsoleFontSize_Label {
            get {
                return ResourceManager.GetString("SettingsView_ConsoleFontSize_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Console/Logs/Yaml Font Size.
        /// </summary>
        public static string SettingsView_ConsoleFontSize_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ConsoleFontSize_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List Row Height.
        /// </summary>
        public static string SettingsView_ListRowHeight_Label {
            get {
                return ResourceManager.GetString("SettingsView_ListRowHeight_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to List Row Height.
        /// </summary>
        public static string SettingsView_ListRowHeight_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ListRowHeight_ToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsView_Theme_Light {
            get {
                return ResourceManager.GetString("SettingsView_Theme_Light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to KubeUI.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PortForwarderListView_Type {
            get {
                return ResourceManager.GetString("PortForwarderListView_Type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PortForwarderListView_Name {
            get {
                return ResourceManager.GetString("PortForwarderListView_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string PortForwarderListView_Namespace {
            get {
                return ResourceManager.GetString("PortForwarderListView_Namespace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PortForwarderListView_Port {
            get {
                return ResourceManager.GetString("PortForwarderListView_Port", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Port.
        /// </summary>
        public static string PortForwarderListView_LocalPort {
            get {
                return ResourceManager.GetString("PortForwarderListView_LocalPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string PortForwarderListView_Connections {
            get {
                return ResourceManager.GetString("PortForwarderListView_Connections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PortForwarderListView_Status {
            get {
                return ResourceManager.GetString("PortForwarderListView_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string PortForwarderListView_OpenInBrowser {
            get {
                return ResourceManager.GetString("PortForwarderListView_OpenInBrowser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PortForwarderListView_Remove {
            get {
                return ResourceManager.GetString("PortForwarderListView_Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An update is available!.
        /// </summary>
        public static string UpdateView_Header {
            get {
                return ResourceManager.GetString("UpdateView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateView_Title {
            get {
                return ResourceManager.GetString("UpdateView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string VisualizationViewModel_Title {
            get {
                return ResourceManager.GetString("VisualizationViewModel_Title", resourceCulture);
            }
        }
    }
}


