//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KubeUI.Avalonia.Assets {
    using System;


    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        public Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KubeUI.Avalonia.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        public static string ClusterErrorView_Header {
            get {
                return ResourceManager.GetString("ClusterErrorView_Header", resourceCulture);
            }
        }
        public static string HomeView_Header {
            get {
                return ResourceManager.GetString("HomeView_Header", resourceCulture);
            }
        }
        public static string AboutView_CreatedBy {
            get {
                return ResourceManager.GetString("AboutView_CreatedBy", resourceCulture);
            }
        }
        public static string AboutView_Version_StringFormat {
            get {
                return ResourceManager.GetString("AboutView_Version_StringFormat", resourceCulture);
            }
        }
        public static string AboutView_Version_FallbackValue {
            get {
                return ResourceManager.GetString("AboutView_Version_FallbackValue", resourceCulture);
            }
        }
        public static string AboutView_Title {
            get {
                return ResourceManager.GetString("AboutView_Title", resourceCulture);
            }
        }
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        public static string AboutView_ContactEmailContent {
            get {
                return ResourceManager.GetString("AboutView_ContactEmailContent", resourceCulture);
            }
        }
        public static string AboutView_ContactEmailUri {
            get {
                return ResourceManager.GetString("AboutView_ContactEmailUri", resourceCulture);
            }
        }
        public static string AboutView_WebsiteContent {
            get {
                return ResourceManager.GetString("AboutView_WebsiteContent", resourceCulture);
            }
        }
        public static string AboutView_WebsiteUri {
            get {
                return ResourceManager.GetString("AboutView_WebsiteUri", resourceCulture);
            }
        }
        public static string MainViewModel_CheckForUpdates_Content {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Content", resourceCulture);
            }
        }
        public static string MainViewModel_CheckForUpdates_Secondary {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Secondary", resourceCulture);
            }
        }
        public static string MainViewModel_CheckForUpdates_Title {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Title", resourceCulture);
            }
        }
        public static string MainViewModel_CheckForUpdates_Updating_Content {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Updating_Content", resourceCulture);
            }
        }
        public static string MainViewModel_CheckForUpdates_Updating_Title {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Updating_Title", resourceCulture);
            }
        }
        public static string MainViewModel_CheckForUpdates_Primary {
            get {
                return ResourceManager.GetString("MainViewModel_CheckForUpdates_Primary", resourceCulture);
            }
        }
        public static string MainView_Menu_File {
            get {
                return ResourceManager.GetString("MainView_Menu_File", resourceCulture);
            }
        }
        public static string MainView_Menu_File_Exit {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Exit", resourceCulture);
            }
        }
        public static string MainView_Menu_Help {
            get {
                return ResourceManager.GetString("MainView_Menu_Help", resourceCulture);
            }
        }
        public static string MainView_Menu_Help_About {
            get {
                return ResourceManager.GetString("MainView_Menu_Help_About", resourceCulture);
            }
        }
        public static string MainView_Menu_Window {
            get {
                return ResourceManager.GetString("MainView_Menu_Window", resourceCulture);
            }
        }
        public static string MainView_Menu_Window_ResetLayout {
            get {
                return ResourceManager.GetString("MainView_Menu_Window_ResetLayout", resourceCulture);
            }
        }
        public static string NavigationViewModel_LoadFolder {
            get {
                return ResourceManager.GetString("NavigationViewModel_LoadFolder", resourceCulture);
            }
        }
        public static string NavigationViewModel_LoadYaml {
            get {
                return ResourceManager.GetString("NavigationViewModel_LoadYaml", resourceCulture);
            }
        }
        public static string PodConsoleViewModel_Title {
            get {
                return ResourceManager.GetString("PodConsoleViewModel_Title", resourceCulture);
            }
        }
        public static string PodLogsViewModel_Title {
            get {
                return ResourceManager.GetString("PodLogsViewModel_Title", resourceCulture);
            }
        }
        public static string PodLogsView_Previous {
            get {
                return ResourceManager.GetString("PodLogsView_Previous", resourceCulture);
            }
        }
        public static string PodLogsView_Timestamps {
            get {
                return ResourceManager.GetString("PodLogsView_Timestamps", resourceCulture);
            }
        }
        public static string ResourcePropertiesViewModel_Title {
            get {
                return ResourceManager.GetString("ResourcePropertiesViewModel_Title", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_Cancel {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Cancel", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_DryRun {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRun", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_DryRunFailed {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRunFailed", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_DryRunSucceeded {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRunSucceeded", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_DryRunSucceededMessage {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_DryRunSucceededMessage", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_SaveFailed {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_SaveFailed", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_SaveSucceeded {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_SaveSucceeded", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_SaveSucceededMessage {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_SaveSucceededMessage", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_Edit {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Edit", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_HideNoisyFields {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_HideNoisyFields", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_Save {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Save", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_ValidationFailed {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_ValidationFailed", resourceCulture);
            }
        }
        public static string ResourceYamlViewer_Undo {
            get {
                return ResourceManager.GetString("ResourceYamlViewer_Undo", resourceCulture);
            }
        }
        public static string ResourceYamlViewModel_Title {
            get {
                return ResourceManager.GetString("ResourceYamlViewModel_Title", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Delete_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Content", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Delete_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Primary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Delete_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Secondary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Delete_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Delete_Title", resourceCulture);
            }
        }
        public static string ResourceListViewModel_PortForward_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Content", resourceCulture);
            }
        }
        public static string ResourceListViewModel_PortForward_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Primary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_PortForward_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Secondary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_PortForward_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_PortForward_Title", resourceCulture);
            }
        }
        public static string ClusterErrorViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterErrorViewModel_Title", resourceCulture);
            }
        }
        public static string ClusterListViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Title", resourceCulture);
            }
        }
        public static string ClusterViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterViewModel_Title", resourceCulture);
            }
        }
        public static string HomeViewModel_Title {
            get {
                return ResourceManager.GetString("HomeViewModel_Title", resourceCulture);
            }
        }
        public static string NavigationViewModel_Title {
            get {
                return ResourceManager.GetString("NavigationViewModel_Title", resourceCulture);
            }
        }
        public static string NavigationView_ToolTip_ClickToConnect {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_ClickToConnect", resourceCulture);
            }
        }
        public static string NavigationView_ToolTip_Connecting {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_Connecting", resourceCulture);
            }
        }
        public static string NavigationView_ToolTip_Errored {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_Errored", resourceCulture);
            }
        }
        public static string NavigationView_ToolTip_Connected {
            get {
                return ResourceManager.GetString("NavigationView_ToolTip_Connected", resourceCulture);
            }
        }
        public static string ResourceConfig_Category_AccessControl {
            get {
                return ResourceManager.GetString("ResourceConfig_Category_AccessControl", resourceCulture);
            }
        }
        public static string ResourceConfig_Category_Configuration {
            get {
                return ResourceManager.GetString("ResourceConfig_Category_Configuration", resourceCulture);
            }
        }
        public static string ResourceConfig_Category_Network {
            get {
                return ResourceManager.GetString("ResourceConfig_Category_Network", resourceCulture);
            }
        }
        public static string ResourceConfig_Category_Storage {
            get {
                return ResourceManager.GetString("ResourceConfig_Category_Storage", resourceCulture);
            }
        }
        public static string ResourceConfig_Category_Workloads {
            get {
                return ResourceManager.GetString("ResourceConfig_Category_Workloads", resourceCulture);
            }
        }
        public static string NavigationView_ContextMenu_Connect {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Connect", resourceCulture);
            }
        }
        public static string NavigationView_ContextMenu_Disconnect {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Disconnect", resourceCulture);
            }
        }
        public static string NavigationView_ContextMenu_Settings {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Settings", resourceCulture);
            }
        }
        public static string NavigationView_ContextMenu_Open {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_Open", resourceCulture);
            }
        }
        public static string NavigationView_ContextMenu_OpenNewTab {
            get {
                return ResourceManager.GetString("NavigationView_ContextMenu_OpenNewTab", resourceCulture);
            }
        }
        public static string ResourceListView_NewResource {
            get {
                return ResourceManager.GetString("ResourceListView_NewResource", resourceCulture);
            }
        }
        public static string ResourceListView_NamespaceLink {
            get {
                return ResourceManager.GetString("ResourceListView_NamespaceLink", resourceCulture);
            }
        }
        public static string ResourceListView_ItemsFormat {
            get {
                return ResourceManager.GetString("ResourceListView_ItemsFormat", resourceCulture);
            }
        }
        public static string ResourceListView_SearchWatermark {
            get {
                return ResourceManager.GetString("ResourceListView_SearchWatermark", resourceCulture);
            }
        }
        public static string VisualizationView_ItemsFormat {
            get {
                return ResourceManager.GetString("VisualizationView_ItemsFormat", resourceCulture);
            }
        }
        public static string VisualizationView_HideNoiseTooltip {
            get {
                return ResourceManager.GetString("VisualizationView_HideNoiseTooltip", resourceCulture);
            }
        }
        public static string VisualizationView_Properties {
            get {
                return ResourceManager.GetString("VisualizationView_Properties", resourceCulture);
            }
        }
        public static string VisualizationView_ViewYaml {
            get {
                return ResourceManager.GetString("VisualizationView_ViewYaml", resourceCulture);
            }
        }
        public static string ClusterListView_Delete {
            get {
                return ResourceManager.GetString("ClusterListView_Delete", resourceCulture);
            }
        }
        public static string ClusterListView_Name {
            get {
                return ResourceManager.GetString("ClusterListView_Name", resourceCulture);
            }
        }
        public static string ClusterListView_KubeConfig {
            get {
                return ResourceManager.GetString("ClusterListView_KubeConfig", resourceCulture);
            }
        }
        public static string ClusterSettingsView_TitleFormat {
            get {
                return ResourceManager.GetString("ClusterSettingsView_TitleFormat", resourceCulture);
            }
        }
        public static string ClusterSettingsView_ManualNamespacesTooltip {
            get {
                return ResourceManager.GetString("ClusterSettingsView_ManualNamespacesTooltip", resourceCulture);
            }
        }
        public static string ClusterSettingsView_NamespacesLabel {
            get {
                return ResourceManager.GetString("ClusterSettingsView_NamespacesLabel", resourceCulture);
            }
        }
        public static string ClusterSettingsView_Add {
            get {
                return ResourceManager.GetString("ClusterSettingsView_Add", resourceCulture);
            }
        }
        public static string ClusterSettingsView_Remove {
            get {
                return ResourceManager.GetString("ClusterSettingsView_Remove", resourceCulture);
            }
        }
        public static string ClusterView_Cpu {
            get {
                return ResourceManager.GetString("ClusterView_Cpu", resourceCulture);
            }
        }
        public static string ClusterView_Memory {
            get {
                return ResourceManager.GetString("ClusterView_Memory", resourceCulture);
            }
        }
        public static string ClusterView_Pods {
            get {
                return ResourceManager.GetString("ClusterView_Pods", resourceCulture);
            }
        }
        public static string ClusterView_Events {
            get {
                return ResourceManager.GetString("ClusterView_Events", resourceCulture);
            }
        }
        public static string ClusterView_CpuCapacity {
            get {
                return ResourceManager.GetString("ClusterView_CpuCapacity", resourceCulture);
            }
        }
        public static string ClusterView_CpuAllocatable {
            get {
                return ResourceManager.GetString("ClusterView_CpuAllocatable", resourceCulture);
            }
        }
        public static string ClusterView_CpuLimits {
            get {
                return ResourceManager.GetString("ClusterView_CpuLimits", resourceCulture);
            }
        }
        public static string ClusterView_CpuRequests {
            get {
                return ResourceManager.GetString("ClusterView_CpuRequests", resourceCulture);
            }
        }
        public static string ClusterView_CpuUsage {
            get {
                return ResourceManager.GetString("ClusterView_CpuUsage", resourceCulture);
            }
        }
        public static string ClusterView_MemoryCapacity {
            get {
                return ResourceManager.GetString("ClusterView_MemoryCapacity", resourceCulture);
            }
        }
        public static string ClusterView_MemoryAllocatable {
            get {
                return ResourceManager.GetString("ClusterView_MemoryAllocatable", resourceCulture);
            }
        }
        public static string ClusterView_MemoryLimits {
            get {
                return ResourceManager.GetString("ClusterView_MemoryLimits", resourceCulture);
            }
        }
        public static string ClusterView_MemoryRequests {
            get {
                return ResourceManager.GetString("ClusterView_MemoryRequests", resourceCulture);
            }
        }
        public static string ClusterView_MemoryUsage {
            get {
                return ResourceManager.GetString("ClusterView_MemoryUsage", resourceCulture);
            }
        }
        public static string ClusterView_PodsCapacity {
            get {
                return ResourceManager.GetString("ClusterView_PodsCapacity", resourceCulture);
            }
        }
        public static string ClusterView_PodsCount {
            get {
                return ResourceManager.GetString("ClusterView_PodsCount", resourceCulture);
            }
        }
        public static string PodLogsView_PodLabel {
            get {
                return ResourceManager.GetString("PodLogsView_PodLabel", resourceCulture);
            }
        }
        public static string PodLogsView_ContainerLabel {
            get {
                return ResourceManager.GetString("PodLogsView_ContainerLabel", resourceCulture);
            }
        }
        public static string PodPropertiesView_ControlledBy {
            get {
                return ResourceManager.GetString("PodPropertiesView_ControlledBy", resourceCulture);
            }
        }
        public static string PodPropertiesView_Name {
            get {
                return ResourceManager.GetString("PodPropertiesView_Name", resourceCulture);
            }
        }
        public static string PodPropertiesView_Image {
            get {
                return ResourceManager.GetString("PodPropertiesView_Image", resourceCulture);
            }
        }
        public static string PodPropertiesView_Status {
            get {
                return ResourceManager.GetString("PodPropertiesView_Status", resourceCulture);
            }
        }
        public static string PodPropertiesView_Node {
            get {
                return ResourceManager.GetString("PodPropertiesView_Node", resourceCulture);
            }
        }
        public static string PodPropertiesView_PodIp {
            get {
                return ResourceManager.GetString("PodPropertiesView_PodIp", resourceCulture);
            }
        }
        public static string PodPropertiesView_PullPolicy {
            get {
                return ResourceManager.GetString("PodPropertiesView_PullPolicy", resourceCulture);
            }
        }
        public static string PodPropertiesView_InitContainers {
            get {
                return ResourceManager.GetString("PodPropertiesView_InitContainers", resourceCulture);
            }
        }
        public static string PodPropertiesView_Containers {
            get {
                return ResourceManager.GetString("PodPropertiesView_Containers", resourceCulture);
            }
        }
        public static string PodContainerCell_NameFormat {
            get {
                return ResourceManager.GetString("PodContainerCell_NameFormat", resourceCulture);
            }
        }
        public static string PodContainerCell_Stopped {
            get {
                return ResourceManager.GetString("PodContainerCell_Stopped", resourceCulture);
            }
        }
        public static string PodContainerCell_Starting {
            get {
                return ResourceManager.GetString("PodContainerCell_Starting", resourceCulture);
            }
        }
        public static string PodContainerCell_Ready {
            get {
                return ResourceManager.GetString("PodContainerCell_Ready", resourceCulture);
            }
        }
        public static string PodContainerCell_InitStopped {
            get {
                return ResourceManager.GetString("PodContainerCell_InitStopped", resourceCulture);
            }
        }
        public static string PodContainerCell_InitStarting {
            get {
                return ResourceManager.GetString("PodContainerCell_InitStarting", resourceCulture);
            }
        }
        public static string PodContainerCell_InitReady {
            get {
                return ResourceManager.GetString("PodContainerCell_InitReady", resourceCulture);
            }
        }
        public static string PodStatusCell_Terminating {
            get {
                return ResourceManager.GetString("PodStatusCell_Terminating", resourceCulture);
            }
        }
        public static string PodStatusCell_Running {
            get {
                return ResourceManager.GetString("PodStatusCell_Running", resourceCulture);
            }
        }
        public static string PodStatusCell_PodCompleted {
            get {
                return ResourceManager.GetString("PodStatusCell_PodCompleted", resourceCulture);
            }
        }
        public static string PodStatusCell_Unknown {
            get {
                return ResourceManager.GetString("PodStatusCell_Unknown", resourceCulture);
            }
        }
        public static string SecretPropertiesView_Data {
            get {
                return ResourceManager.GetString("SecretPropertiesView_Data", resourceCulture);
            }
        }
        public static string SecretPropertiesView_Certificates {
            get {
                return ResourceManager.GetString("SecretPropertiesView_Certificates", resourceCulture);
            }
        }
        public static string PortForwarderListView_Type {
            get {
                return ResourceManager.GetString("PortForwarderListView_Type", resourceCulture);
            }
        }
        public static string PortForwarderListView_Name {
            get {
                return ResourceManager.GetString("PortForwarderListView_Name", resourceCulture);
            }
        }
        public static string PortForwarderListView_Namespace {
            get {
                return ResourceManager.GetString("PortForwarderListView_Namespace", resourceCulture);
            }
        }
        public static string PortForwarderListView_Port {
            get {
                return ResourceManager.GetString("PortForwarderListView_Port", resourceCulture);
            }
        }
        public static string PortForwarderListView_LocalPort {
            get {
                return ResourceManager.GetString("PortForwarderListView_LocalPort", resourceCulture);
            }
        }
        public static string PortForwarderListView_Connections {
            get {
                return ResourceManager.GetString("PortForwarderListView_Connections", resourceCulture);
            }
        }
        public static string PortForwarderListView_Status {
            get {
                return ResourceManager.GetString("PortForwarderListView_Status", resourceCulture);
            }
        }
        public static string PortForwarderListView_OpenInBrowser {
            get {
                return ResourceManager.GetString("PortForwarderListView_OpenInBrowser", resourceCulture);
            }
        }
        public static string PortForwarderListView_Remove {
            get {
                return ResourceManager.GetString("PortForwarderListView_Remove", resourceCulture);
            }
        }
        public static string PortForwarderListViewModel_Remove_Content {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Content", resourceCulture);
            }
        }
        public static string PortForwarderListViewModel_Remove_Primary {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Primary", resourceCulture);
            }
        }
        public static string PortForwarderListViewModel_Remove_Secondary {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Secondary", resourceCulture);
            }
        }
        public static string PortForwarderListViewModel_Remove_Title {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Remove_Title", resourceCulture);
            }
        }
        public static string Action_Copy {
            get {
                return ResourceManager.GetString("Action_Copy", resourceCulture);
            }
        }
        public static string Action_Cut {
            get {
                return ResourceManager.GetString("Action_Cut", resourceCulture);
            }
        }
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        public static string Action_Paste {
            get {
                return ResourceManager.GetString("Action_Paste", resourceCulture);
            }
        }
        public static string Action_Redo {
            get {
                return ResourceManager.GetString("Action_Redo", resourceCulture);
            }
        }
        public static string Action_Undo {
            get {
                return ResourceManager.GetString("Action_Undo", resourceCulture);
            }
        }
        public static string PortForwarderListViewModel_Title {
            get {
                return ResourceManager.GetString("PortForwarderListViewModel_Title", resourceCulture);
            }
        }
        public static string MainView_Menu_File_Clusters {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Clusters", resourceCulture);
            }
        }
        public static string ClusterListViewModel_Delete_Content {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Content", resourceCulture);
            }
        }
        public static string ClusterListViewModel_Delete_Primary {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Primary", resourceCulture);
            }
        }
        public static string ClusterListViewModel_Delete_Secondary {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Secondary", resourceCulture);
            }
        }
        public static string ClusterListViewModel_Delete_Title {
            get {
                return ResourceManager.GetString("ClusterListViewModel_Delete_Title", resourceCulture);
            }
        }
        public static string MainView_Menu_Window_SwitchTheme {
            get {
                return ResourceManager.GetString("MainView_Menu_Window_SwitchTheme", resourceCulture);
            }
        }
        public static string MainView_Menu_File_Settings {
            get {
                return ResourceManager.GetString("MainView_Menu_File_Settings", resourceCulture);
            }
        }
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        public static string SettingsView_Theme {
            get {
                return ResourceManager.GetString("SettingsView_Theme", resourceCulture);
            }
        }
        public static string SettingsView_Theme_Default {
            get {
                return ResourceManager.GetString("SettingsView_Theme_Default", resourceCulture);
            }
        }
        public static string SettingsView_Theme_Light {
            get {
                return ResourceManager.GetString("SettingsView_Theme_Light", resourceCulture);
            }
        }
        public static string SettingsView_Theme_Dark {
            get {
                return ResourceManager.GetString("SettingsView_Theme_Dark", resourceCulture);
            }
        }
        public static string SettingsView_Logging_Label {
            get {
                return ResourceManager.GetString("SettingsView_Logging_Label", resourceCulture);
            }
        }
        public static string SettingsView_Logging_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_Logging_ToolTip", resourceCulture);
            }
        }
        public static string SettingsView_Telemetry_Label {
            get {
                return ResourceManager.GetString("SettingsView_Telemetry_Label", resourceCulture);
            }
        }
        public static string SettingsView_Telemetry_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_Telemetry_ToolTip", resourceCulture);
            }
        }
        public static string SettingsView_PreRelease_Label {
            get {
                return ResourceManager.GetString("SettingsView_PreRelease_Label", resourceCulture);
            }
        }
        public static string SettingsView_PreRelease_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_PreRelease_ToolTip", resourceCulture);
            }
        }
        public static string SettingsView_FontSize_Label {
            get {
                return ResourceManager.GetString("SettingsView_FontSize_Label", resourceCulture);
            }
        }
        public static string SettingsView_FontSize_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_FontSize_ToolTip", resourceCulture);
            }
        }
        public static string SettingsView_ConsoleFontSize_Label {
            get {
                return ResourceManager.GetString("SettingsView_ConsoleFontSize_Label", resourceCulture);
            }
        }
        public static string SettingsView_ConsoleFontSize_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ConsoleFontSize_ToolTip", resourceCulture);
            }
        }
        public static string SettingsView_ListRowHeight_Label {
            get {
                return ResourceManager.GetString("SettingsView_ListRowHeight_Label", resourceCulture);
            }
        }
        public static string SettingsView_ListRowHeight_ToolTip {
            get {
                return ResourceManager.GetString("SettingsView_ListRowHeight_ToolTip", resourceCulture);
            }
        }
        public static string VisualizationViewModel_Title {
            get {
                return ResourceManager.GetString("VisualizationViewModel_Title", resourceCulture);
            }
        }
        public static string ResourcePropertiesView_Name {
            get {
                return ResourceManager.GetString("ResourcePropertiesView_Name", resourceCulture);
            }
        }
        public static string ResourcePropertiesView_Namespace {
            get {
                return ResourceManager.GetString("ResourcePropertiesView_Namespace", resourceCulture);
            }
        }
        public static string ResourcePropertiesView_Created {
            get {
                return ResourceManager.GetString("ResourcePropertiesView_Created", resourceCulture);
            }
        }
        public static string Address_Type {
            get {
                return ResourceManager.GetString("Address Type", resourceCulture);
            }
        }
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        public static string Active_Deadline_Seconds {
            get {
                return ResourceManager.GetString("Active Deadline Seconds", resourceCulture);
            }
        }
        public static string Active_Jobs {
            get {
                return ResourceManager.GetString("Active Jobs", resourceCulture);
            }
        }
        public static string Active_Pods {
            get {
                return ResourceManager.GetString("Active Pods", resourceCulture);
            }
        }
        public static string Acquire_Time {
            get {
                return ResourceManager.GetString("Acquire Time", resourceCulture);
            }
        }
        public static string Accepted_Kind {
            get {
                return ResourceManager.GetString("Accepted Kind", resourceCulture);
            }
        }
        public static string Aggregation_Selectors {
            get {
                return ResourceManager.GetString("Aggregation Selectors", resourceCulture);
            }
        }
        public static string Allow_Volume_Expansion {
            get {
                return ResourceManager.GetString("Allow Volume Expansion", resourceCulture);
            }
        }
        public static string Allocatable_Entries {
            get {
                return ResourceManager.GetString("Allocatable Entries", resourceCulture);
            }
        }
        public static string Architecture {
            get {
                return ResourceManager.GetString("Architecture", resourceCulture);
            }
        }
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        public static string Available_Replicas {
            get {
                return ResourceManager.GetString("Available Replicas", resourceCulture);
            }
        }
        public static string Automount_Token {
            get {
                return ResourceManager.GetString("Automount Token", resourceCulture);
            }
        }
        public static string Backoff_Limit {
            get {
                return ResourceManager.GetString("Backoff Limit", resourceCulture);
            }
        }
        public static string Binary_Data {
            get {
                return ResourceManager.GetString("Binary Data", resourceCulture);
            }
        }
        public static string Capacity_Entries {
            get {
                return ResourceManager.GetString("Capacity Entries", resourceCulture);
            }
        }
        public static string Claim_Name {
            get {
                return ResourceManager.GetString("Claim Name", resourceCulture);
            }
        }
        public static string Cluster_IP {
            get {
                return ResourceManager.GetString("Cluster IP", resourceCulture);
            }
        }
        public static string Cluster_IPs {
            get {
                return ResourceManager.GetString("Cluster IPs", resourceCulture);
            }
        }
        public static string Completions {
            get {
                return ResourceManager.GetString("Completions", resourceCulture);
            }
        }
        public static string Concurrency_Policy {
            get {
                return ResourceManager.GetString("Concurrency Policy", resourceCulture);
            }
        }
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        public static string Container_Runtime {
            get {
                return ResourceManager.GetString("Container Runtime", resourceCulture);
            }
        }
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        public static string Current_Healthy {
            get {
                return ResourceManager.GetString("Current Healthy", resourceCulture);
            }
        }
        public static string Current_Replicas {
            get {
                return ResourceManager.GetString("Current Replicas", resourceCulture);
            }
        }
        public static string Current_Revision {
            get {
                return ResourceManager.GetString("Current Revision", resourceCulture);
            }
        }
        public static string Current_Scheduled {
            get {
                return ResourceManager.GetString("Current Scheduled", resourceCulture);
            }
        }
        public static string Current_NumberScheduled {
            get {
                return ResourceManager.GetString("Current NumberScheduled", resourceCulture);
            }
        }
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        public static string Desired_Healthy {
            get {
                return ResourceManager.GetString("Desired Healthy", resourceCulture);
            }
        }
        public static string Desired_Replicas {
            get {
                return ResourceManager.GetString("Desired Replicas", resourceCulture);
            }
        }
        public static string Desired_Scheduled {
            get {
                return ResourceManager.GetString("Desired Scheduled", resourceCulture);
            }
        }
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        public static string Disruptions_Allowed {
            get {
                return ResourceManager.GetString("Disruptions Allowed", resourceCulture);
            }
        }
        public static string Egress_Rules {
            get {
                return ResourceManager.GetString("Egress Rules", resourceCulture);
            }
        }
        public static string Endpoints {
            get {
                return ResourceManager.GetString("Endpoints", resourceCulture);
            }
        }
        public static string Expected_Pods {
            get {
                return ResourceManager.GetString("Expected Pods", resourceCulture);
            }
        }
        public static string External_IPs {
            get {
                return ResourceManager.GetString("External IPs", resourceCulture);
            }
        }
        public static string External_Name {
            get {
                return ResourceManager.GetString("External Name", resourceCulture);
            }
        }
        public static string External_Traffic_Policy {
            get {
                return ResourceManager.GetString("External Traffic Policy", resourceCulture);
            }
        }
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        public static string Failed_History_Limit {
            get {
                return ResourceManager.GetString("Failed History Limit", resourceCulture);
            }
        }
        public static string Field_Path {
            get {
                return ResourceManager.GetString("Field Path", resourceCulture);
            }
        }
        public static string First_Seen {
            get {
                return ResourceManager.GetString("First Seen", resourceCulture);
            }
        }
        public static string Fully_Labeled_Replicas {
            get {
                return ResourceManager.GetString("Fully Labeled Replicas", resourceCulture);
            }
        }
        public static string Global_Default {
            get {
                return ResourceManager.GetString("Global Default", resourceCulture);
            }
        }
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        public static string Handler {
            get {
                return ResourceManager.GetString("Handler", resourceCulture);
            }
        }
        public static string Health_Check_Node_Port {
            get {
                return ResourceManager.GetString("Health Check Node Port", resourceCulture);
            }
        }
        public static string Holder_Identity {
            get {
                return ResourceManager.GetString("Holder Identity", resourceCulture);
            }
        }
        public static string Image_Pull_Secrets {
            get {
                return ResourceManager.GetString("Image Pull Secrets", resourceCulture);
            }
        }
        public static string Immutable {
            get {
                return ResourceManager.GetString("Immutable", resourceCulture);
            }
        }
        public static string Ingress_Class {
            get {
                return ResourceManager.GetString("Ingress Class", resourceCulture);
            }
        }
        public static string Ingress_Rules {
            get {
                return ResourceManager.GetString("Ingress Rules", resourceCulture);
            }
        }
        public static string InvolvedObject {
            get {
                return ResourceManager.GetString("InvolvedObject", resourceCulture);
            }
        }
        public static string Internal_Traffic_Policy {
            get {
                return ResourceManager.GetString("Internal Traffic Policy", resourceCulture);
            }
        }
        public static string Kernel_Version {
            get {
                return ResourceManager.GetString("Kernel Version", resourceCulture);
            }
        }
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        public static string Kubelet_Version {
            get {
                return ResourceManager.GetString("Kubelet Version", resourceCulture);
            }
        }
        public static string Last_Phase_Transition {
            get {
                return ResourceManager.GetString("Last Phase Transition", resourceCulture);
            }
        }
        public static string Last_Schedule_Time {
            get {
                return ResourceManager.GetString("Last Schedule Time", resourceCulture);
            }
        }
        public static string Last_Seen {
            get {
                return ResourceManager.GetString("Last Seen", resourceCulture);
            }
        }
        public static string Last_Successful_Time {
            get {
                return ResourceManager.GetString("Last Successful Time", resourceCulture);
            }
        }
        public static string Lease_Duration_Seconds {
            get {
                return ResourceManager.GetString("Lease Duration Seconds", resourceCulture);
            }
        }
        public static string Lease_Transitions {
            get {
                return ResourceManager.GetString("Lease Transitions", resourceCulture);
            }
        }
        public static string Load_Balancer_Class {
            get {
                return ResourceManager.GetString("Load Balancer Class", resourceCulture);
            }
        }
        public static string Load_Balancer_Ingress {
            get {
                return ResourceManager.GetString("Load Balancer Ingress", resourceCulture);
            }
        }
        public static string Load_Balancer_IP {
            get {
                return ResourceManager.GetString("Load Balancer IP", resourceCulture);
            }
        }
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        public static string Max_Replicas {
            get {
                return ResourceManager.GetString("Max Replicas", resourceCulture);
            }
        }
        public static string Max_Unavailable {
            get {
                return ResourceManager.GetString("Max Unavailable", resourceCulture);
            }
        }
        public static string Min_Available {
            get {
                return ResourceManager.GetString("Min Available", resourceCulture);
            }
        }
        public static string Min_Ready_Seconds {
            get {
                return ResourceManager.GetString("Min Ready Seconds", resourceCulture);
            }
        }
        public static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        public static string Misscheduled {
            get {
                return ResourceManager.GetString("Misscheduled", resourceCulture);
            }
        }
        public static string Mount_Options {
            get {
                return ResourceManager.GetString("Mount Options", resourceCulture);
            }
        }
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        public static string Node_Selector_Entries {
            get {
                return ResourceManager.GetString("Node Selector Entries", resourceCulture);
            }
        }
        public static string NoEventsFound {
            get {
                return ResourceManager.GetString("NoEventsFound", resourceCulture);
            }
        }
        public static string Observed_Generation {
            get {
                return ResourceManager.GetString("Observed Generation", resourceCulture);
            }
        }
        public static string Operating_System {
            get {
                return ResourceManager.GetString("Operating System", resourceCulture);
            }
        }
        public static string Parallelism {
            get {
                return ResourceManager.GetString("Parallelism", resourceCulture);
            }
        }
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        public static string Parameters_Kind {
            get {
                return ResourceManager.GetString("Parameters Kind", resourceCulture);
            }
        }
        public static string Parameters_Name {
            get {
                return ResourceManager.GetString("Parameters Name", resourceCulture);
            }
        }
        public static string Parameters_Namespace {
            get {
                return ResourceManager.GetString("Parameters Namespace", resourceCulture);
            }
        }
        public static string Parameters_Scope {
            get {
                return ResourceManager.GetString("Parameters Scope", resourceCulture);
            }
        }
        public static string Phase {
            get {
                return ResourceManager.GetString("Phase", resourceCulture);
            }
        }
        public static string Policy_Types {
            get {
                return ResourceManager.GetString("Policy Types", resourceCulture);
            }
        }
        public static string Pod_IPs {
            get {
                return ResourceManager.GetString("Pod IPs", resourceCulture);
            }
        }
        public static string Pod_Management_Policy {
            get {
                return ResourceManager.GetString("Pod Management Policy", resourceCulture);
            }
        }
        public static string Pod_Selector_Labels {
            get {
                return ResourceManager.GetString("Pod Selector Labels", resourceCulture);
            }
        }
        public static string Ports {
            get {
                return ResourceManager.GetString("Ports", resourceCulture);
            }
        }
        public static string Preemption_Policy {
            get {
                return ResourceManager.GetString("Preemption Policy", resourceCulture);
            }
        }
        public static string Progress_Deadline_Seconds {
            get {
                return ResourceManager.GetString("Progress Deadline Seconds", resourceCulture);
            }
        }
        public static string Provisioner {
            get {
                return ResourceManager.GetString("Provisioner", resourceCulture);
            }
        }
        public static string Publish_Not_Ready_Addresses {
            get {
                return ResourceManager.GetString("Publish Not Ready Addresses", resourceCulture);
            }
        }
        public static string QoS_Class {
            get {
                return ResourceManager.GetString("QoS Class", resourceCulture);
            }
        }
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        public static string Ready_Replicas {
            get {
                return ResourceManager.GetString("Ready Replicas", resourceCulture);
            }
        }
        public static string Reclaim_Policy {
            get {
                return ResourceManager.GetString("Reclaim Policy", resourceCulture);
            }
        }
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        public static string Requested_Storage {
            get {
                return ResourceManager.GetString("Requested Storage", resourceCulture);
            }
        }
        public static string Replicas {
            get {
                return ResourceManager.GetString("Replicas", resourceCulture);
            }
        }
        public static string Revision_History_Limit {
            get {
                return ResourceManager.GetString("Revision History Limit", resourceCulture);
            }
        }
        public static string Role_Kind {
            get {
                return ResourceManager.GetString("Role Kind", resourceCulture);
            }
        }
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role Name", resourceCulture);
            }
        }
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        public static string Secrets {
            get {
                return ResourceManager.GetString("Secrets", resourceCulture);
            }
        }
        public static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        public static string Selector_Labels {
            get {
                return ResourceManager.GetString("Selector Labels", resourceCulture);
            }
        }
        public static string Session_Affinity {
            get {
                return ResourceManager.GetString("Session Affinity", resourceCulture);
            }
        }
        public static string Service_Account {
            get {
                return ResourceManager.GetString("Service Account", resourceCulture);
            }
        }
        public static string Service_Name {
            get {
                return ResourceManager.GetString("Service Name", resourceCulture);
            }
        }
        public static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        public static string Starting_Deadline_Seconds {
            get {
                return ResourceManager.GetString("Starting Deadline Seconds", resourceCulture);
            }
        }
        public static string Storage_Class {
            get {
                return ResourceManager.GetString("Storage Class", resourceCulture);
            }
        }
        public static string Strategy_Type {
            get {
                return ResourceManager.GetString("Strategy Type", resourceCulture);
            }
        }
        public static string Sub_object {
            get {
                return ResourceManager.GetString("Sub-object", resourceCulture);
            }
        }
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        public static string Successful_History_Limit {
            get {
                return ResourceManager.GetString("Successful History Limit", resourceCulture);
            }
        }
        public static string Suspend {
            get {
                return ResourceManager.GetString("Suspend", resourceCulture);
            }
        }
        public static string Taints {
            get {
                return ResourceManager.GetString("Taints", resourceCulture);
            }
        }
        public static string Time_Zone {
            get {
                return ResourceManager.GetString("Time Zone", resourceCulture);
            }
        }
        public static string Tolerations {
            get {
                return ResourceManager.GetString("Tolerations", resourceCulture);
            }
        }
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        public static string Unavailable_Replicas {
            get {
                return ResourceManager.GetString("Unavailable Replicas", resourceCulture);
            }
        }
        public static string Update_Revision {
            get {
                return ResourceManager.GetString("Update Revision", resourceCulture);
            }
        }
        public static string Update_Strategy {
            get {
                return ResourceManager.GetString("Update Strategy", resourceCulture);
            }
        }
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        public static string Updated_Replicas {
            get {
                return ResourceManager.GetString("Updated Replicas", resourceCulture);
            }
        }
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        public static string Volumes {
            get {
                return ResourceManager.GetString("Volumes", resourceCulture);
            }
        }
        public static string Volume_Binding_Mode {
            get {
                return ResourceManager.GetString("Volume Binding Mode", resourceCulture);
            }
        }
        public static string Volume_Name {
            get {
                return ResourceManager.GetString("Volume Name", resourceCulture);
            }
        }
        public static string Webhooks {
            get {
                return ResourceManager.GetString("Webhooks", resourceCulture);
            }
        }
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        public static string Load_Balancer_Entries {
            get {
                return ResourceManager.GetString("Load Balancer Entries", resourceCulture);
            }
        }
        public static string NamespaceProperty {
            get {
                return ResourceManager.GetString("NamespaceProperty", resourceCulture);
            }
        }
        public static string Overhead_Entries {
            get {
                return ResourceManager.GetString("Overhead Entries", resourceCulture);
            }
        }
        public static string Pod_Volumes {
            get {
                return ResourceManager.GetString("Pod Volumes", resourceCulture);
            }
        }
        public static string ResourceEventsView_Title {
            get {
                return ResourceManager.GetString("ResourceEventsView_Title", resourceCulture);
            }
        }
        public static string ResourceEventsView_Source {
            get {
                return ResourceManager.GetString("ResourceEventsView_Source", resourceCulture);
            }
        }
        public static string ResourceEventsView_Count {
            get {
                return ResourceManager.GetString("ResourceEventsView_Count", resourceCulture);
            }
        }
        public static string ResourceEventsView_SubObject {
            get {
                return ResourceManager.GetString("ResourceEventsView_SubObject", resourceCulture);
            }
        }
        public static string ResourceEventsView_LastSeen {
            get {
                return ResourceManager.GetString("ResourceEventsView_LastSeen", resourceCulture);
            }
        }
        public static string ResourceListView_SelectNamespace {
            get {
                return ResourceManager.GetString("ResourceListView_SelectNamespace", resourceCulture);
            }
        }
        public static string ClusterSettingsViewModel_Title {
            get {
                return ResourceManager.GetString("ClusterSettingsViewModel_Title", resourceCulture);
            }
        }
        public static string Cluster_Missing_Namespace_Permission_Title {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Title", resourceCulture);
            }
        }
        public static string Cluster_Missing_Namespace_Permission_Content {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Content", resourceCulture);
            }
        }
        public static string Cluster_Missing_Namespace_Permission_Primary {
            get {
                return ResourceManager.GetString("Cluster_Missing_Namespace_Permission_Primary", resourceCulture);
            }
        }
        public static string ResourceYamlView_WordWrap {
            get {
                return ResourceManager.GetString("ResourceYamlView_WordWrap", resourceCulture);
            }
        }
        public static string PodLogsView_WordWrap {
            get {
                return ResourceManager.GetString("PodLogsView_WordWrap", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Restart_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Title", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Restart_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Content", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Restart_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Primary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_Restart_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_Restart_Secondary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_CordonNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Title", resourceCulture);
            }
        }
        public static string ResourceListViewModel_CordonNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Content", resourceCulture);
            }
        }
        public static string ResourceListViewModel_CordonNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Primary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_CordonNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_CordonNode_Secondary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_UnCordonNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Content", resourceCulture);
            }
        }
        public static string ResourceListViewModel_UnCordonNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Primary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_UnCordonNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Secondary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_UnCordonNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_UnCordonNode_Title", resourceCulture);
            }
        }
        public static string ResourceListViewModel_DrainNode_Content {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Content", resourceCulture);
            }
        }
        public static string ResourceListViewModel_DrainNode_Title {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Title", resourceCulture);
            }
        }
        public static string ResourceListViewModel_DrainNode_Secondary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Secondary", resourceCulture);
            }
        }
        public static string ResourceListViewModel_DrainNode_Primary {
            get {
                return ResourceManager.GetString("ResourceListViewModel_DrainNode_Primary", resourceCulture);
            }
        }
        public static string MainView_Menu_File_LoadKubeConfig {
            get {
                return ResourceManager.GetString("MainView_Menu_File_LoadKubeConfig", resourceCulture);
            }
        }
        public static string MainView_Menu_File_LoadKubeConfig_Open {
            get {
                return ResourceManager.GetString("MainView_Menu_File_LoadKubeConfig_Open", resourceCulture);
            }
        }
        public static string PodLogsView_Clear {
            get {
                return ResourceManager.GetString("PodLogsView_Clear", resourceCulture);
            }
        }
        public static string PodLogsView_JumpToPresent {
            get {
                return ResourceManager.GetString("PodLogsView_JumpToPresent", resourceCulture);
            }
        }
        public static string PodLogsView_Download {
            get {
                return ResourceManager.GetString("PodLogsView_Download", resourceCulture);
            }
        }
        public static string PodLogsView_ShowResourceNames {
            get {
                return ResourceManager.GetString("PodLogsView_ShowResourceNames", resourceCulture);
            }
        }
        public static string PodLogsView_AllPods {
            get {
                return ResourceManager.GetString("PodLogsView_AllPods", resourceCulture);
            }
        }
        public static string PodLogsView_AllContainers {
            get {
                return ResourceManager.GetString("PodLogsView_AllContainers", resourceCulture);
            }
        }
        public static string PodLogsView_Controller {
            get {
                return ResourceManager.GetString("PodLogsView_Controller", resourceCulture);
            }
        }
        public static string PodLogsView_Search {
            get {
                return ResourceManager.GetString("PodLogsView_Search", resourceCulture);
            }
        }
        public static string PodLogsView_SearchPrevious {
            get {
                return ResourceManager.GetString("PodLogsView_SearchPrevious", resourceCulture);
            }
        }
        public static string PodLogsView_SearchNext {
            get {
                return ResourceManager.GetString("PodLogsView_SearchNext", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Apply {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Apply", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Any {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Any", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_And {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_And", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Between {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Between", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Clear {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Clear", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Condition {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Condition", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Contains {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Contains", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotContains {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotContains", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_EndsWith {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_EndsWith", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotEndsWith {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotEndsWith", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Equals {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Equals", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotEquals {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotEquals", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_GreaterThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_GreaterThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotGreaterThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotGreaterThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_GreaterThanOrEqual", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotGreaterThanOrEqual", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_LessThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_LessThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotLessThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotLessThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_LessThanOrEqual {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_LessThanOrEqual", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotLessThanOrEqual {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotLessThanOrEqual", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotBetween {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotBetween", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NewerThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NewerThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotNewerThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotNewerThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_OlderThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_OlderThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotOlderThan {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotOlderThan", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_StartsWith {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_StartsWith", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_NotStartsWith {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_NotStartsWith", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Value {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Value", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Minutes {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Minutes", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Hours {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Hours", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Days {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Days", resourceCulture);
            }
        }
        public static string DataGridFilterFlyout_Months {
            get {
                return ResourceManager.GetString("DataGridFilterFlyout_Months", resourceCulture);
            }
        }
        public static string UpdateView_Title {
            get {
                return ResourceManager.GetString("UpdateView_Title", resourceCulture);
            }
        }
        public static string AboutView_Contact {
            get {
                return ResourceManager.GetString("AboutView_Contact", resourceCulture);
            }
        }
        public static string AboutView_Website {
            get {
                return ResourceManager.GetString("AboutView_Website", resourceCulture);
            }
        }
        public static string UpdateView_Header {
            get {
                return ResourceManager.GetString("UpdateView_Header", resourceCulture);
            }
        }
        public static string Access_Modes {
            get {
                return ResourceManager.GetString("Access Modes", resourceCulture);
            }
        }
        public static string Allowed_Topologies {
            get {
                return ResourceManager.GetString("Allowed Topologies", resourceCulture);
            }
        }
        public static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        public static string Completion_Mode {
            get {
                return ResourceManager.GetString("Completion Mode", resourceCulture);
            }
        }
        public static string Completion_Time {
            get {
                return ResourceManager.GetString("Completion Time", resourceCulture);
            }
        }
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        public static string Finalizers {
            get {
                return ResourceManager.GetString("Finalizers", resourceCulture);
            }
        }
        public static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        public static string Limits {
            get {
                return ResourceManager.GetString("Limits", resourceCulture);
            }
        }
        public static string Min_Replicas {
            get {
                return ResourceManager.GetString("Min Replicas", resourceCulture);
            }
        }
        public static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        public static string Renew_Time {
            get {
                return ResourceManager.GetString("Renew Time", resourceCulture);
            }
        }
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        public static string Spec_Hard {
            get {
                return ResourceManager.GetString("Spec Hard", resourceCulture);
            }
        }
        public static string Spec_Scopes {
            get {
                return ResourceManager.GetString("Spec Scopes", resourceCulture);
            }
        }
        public static string Status_Hard {
            get {
                return ResourceManager.GetString("Status Hard", resourceCulture);
            }
        }
        public static string Status_Used {
            get {
                return ResourceManager.GetString("Status Used", resourceCulture);
            }
        }
        public static string Stored_Versions {
            get {
                return ResourceManager.GetString("Stored Versions", resourceCulture);
            }
        }
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        public static string TLS_Entries {
            get {
                return ResourceManager.GetString("TLS Entries", resourceCulture);
            }
        }
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        public static string Volume_Mode {
            get {
                return ResourceManager.GetString("Volume Mode", resourceCulture);
            }
        }
        public static string PodLogsView_AutoScrollToBottom {
            get {
                return ResourceManager.GetString("PodLogsView_AutoScrollToBottom", resourceCulture);
            }
        }
        public static string ClusterSettingsView_DebugContainerImageLabel {
            get {
                return ResourceManager.GetString("ClusterSettingsView_DebugContainerImageLabel", resourceCulture);
            }
        }
        public static string ClusterSettingsView_DebugContainerImageTooltip {
            get {
                return ResourceManager.GetString("ClusterSettingsView_DebugContainerImageTooltip", resourceCulture);
            }
        }
        public static string PodContainerCell_TypeFormat {
            get {
                return ResourceManager.GetString("PodContainerCell_TypeFormat", resourceCulture);
            }
        }
        public static string PodContainerCell_StatusFormat {
            get {
                return ResourceManager.GetString("PodContainerCell_StatusFormat", resourceCulture);
            }
        }
        public static string PodContainerCell_RestartsFormat {
            get {
                return ResourceManager.GetString("PodContainerCell_RestartsFormat", resourceCulture);
            }
        }
        public static string PodContainerCell_ImageFormat {
            get {
                return ResourceManager.GetString("PodContainerCell_ImageFormat", resourceCulture);
            }
        }
        public static string PodPropertiesView_EphemeralContainers {
            get {
                return ResourceManager.GetString("PodPropertiesView_EphemeralContainers", resourceCulture);
            }
        }
        public static string MainView_Menu_File_ImportAksCluster {
            get {
                return ResourceManager.GetString("MainView_Menu_File_ImportAksCluster", resourceCulture);
            }
        }
        public static string ImportAksClusterViewModel_Title {
            get {
                return ResourceManager.GetString("ImportAksClusterViewModel_Title", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Description {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Description", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Prerequisites {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Prerequisites", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Subscription {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Subscription", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Tenant {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Tenant", resourceCulture);
            }
        }
        public static string ImportAksClusterView_TenantId {
            get {
                return ResourceManager.GetString("ImportAksClusterView_TenantId", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Cluster {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Cluster", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Refresh {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Refresh", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Import {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Import", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Importing {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Importing", resourceCulture);
            }
        }
        public static string ImportAksClusterView_Imported {
            get {
                return ResourceManager.GetString("ImportAksClusterView_Imported", resourceCulture);
            }
        }
        public static string ImportAksClusterView_ResourceGroupFormat {
            get {
                return ResourceManager.GetString("ImportAksClusterView_ResourceGroupFormat", resourceCulture);
            }
        }
        public static string ImportAksClusterView_VersionFormat {
            get {
                return ResourceManager.GetString("ImportAksClusterView_VersionFormat", resourceCulture);
            }
        }
        public static string CloudClusterConnectView_Description {
            get {
                return ResourceManager.GetString("CloudClusterConnectView_Description", resourceCulture);
            }
        }
        public static string CloudClusterConnectView_SubscriptionFirst {
            get {
                return ResourceManager.GetString("CloudClusterConnectView_SubscriptionFirst", resourceCulture);
            }
        }
        public static string CloudClusterConnectView_AksOnly {
            get {
                return ResourceManager.GetString("CloudClusterConnectView_AksOnly", resourceCulture);
            }
        }
        public static string V1PodConfig_DebugContainer {
            get {
                return ResourceManager.GetString("V1PodConfig_DebugContainer", resourceCulture);
            }
        }
        public static string V1PodConfig_DebugContainer_Pod {
            get {
                return ResourceManager.GetString("V1PodConfig_DebugContainer_Pod", resourceCulture);
            }
        }
        public static string V1PodConfig_DebugContainer_Error {
            get {
                return ResourceManager.GetString("V1PodConfig_DebugContainer_Error", resourceCulture);
            }
        }
        public static string ImportAksClusterView_NoSubscriptions {
            get {
                return ResourceManager.GetString("ImportAksClusterView_NoSubscriptions", resourceCulture);
            }
        }
        public static string ImportAksClusterView_AzureCliSignedIn {
            get {
                return ResourceManager.GetString("ImportAksClusterView_AzureCliSignedIn", resourceCulture);
            }
        }
        public static string ImportAksClusterView_AzureCliNotSignedIn {
            get {
                return ResourceManager.GetString("ImportAksClusterView_AzureCliNotSignedIn", resourceCulture);
            }
        }
        public static string ImportAksClusterView_AccountFormat {
            get {
                return ResourceManager.GetString("ImportAksClusterView_AccountFormat", resourceCulture);
            }
        }
    }
}