<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" Version="12.1.2" />
    <PackageReference Include="KokoroSharp.CPU" Version="0.8.4" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KubeUI.Avalonia.Tests\KubeUI.Avalonia.Tests.csproj" />
    <ProjectReference Include="..\KubeUI.Testing\KubeUI.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="KubeUI.Avalonia" />
  </ItemGroup>

  <Target Name="DisableDeclarativeAnalyzer" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="'%(Filename)' == 'Avalonia.Markup.Declarative.SourceGenerator'" />
    </ItemGroup>
  </Target>

</Project>
