<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless.XUnit" Version="12.1.1" />
    <PackageReference Include="dotacp.client" Version="2026.7.19" PrivateAssets="all" />
    <PackageReference Include="dotacp.protocol" Version="2026.7.19" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
    <PackageReference Include="Microsoft.Testing.Extensions.CrashDump" Version="2.3.3" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" Version="2.3.3" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3" />
    <PackageReference Include="StreamJsonRpc" Version="2.25.29" PrivateAssets="all" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KubeUI.Avalonia\KubeUI.Avalonia.csproj" />
    <ProjectReference Include="..\..\src\KubeUI.Desktop\KubeUI.Desktop.csproj" />
    <ProjectReference Include="..\..\src\KubeUI.Kubernetes\KubeUI.Kubernetes.csproj" />
    <ProjectReference Include="..\KubeUI.Testing\KubeUI.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="KubeUI.Benchmarks" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="KubeUI.Avalonia" />
    <Using Include="KubeUI.Kubernetes" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectCapability Include="Avalonia" />
  </ItemGroup>

  <Target Name="DisableAnalyzers" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="@(Analyzer)" Condition="'%(Filename)' == 'Avalonia.Markup.Declarative.SourceGenerator'" />
    </ItemGroup>
  </Target>

</Project>
