name: Build Test

on:
  workflow_call:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Build
        run: dotnet build --configuration Release -p:WarningLevel=0

      - name: Test Avalonia
        run: |
          dotnet test \
            --project tests/KubeUI.Avalonia.Tests/KubeUI.Avalonia.Tests.csproj \
            --configuration Release \
            --no-build \
            --hangdump \
            --hangdump-timeout 1m \
            --report-xunit-trx \
            --report-xunit-trx-filename avalonia-test-results.trx \
            --coverage \
            --coverage-output-format cobertura \
            --coverage-output coverage-avalonia.cobertura.xml
        env:
          KUBEUI_RUN_KIND_TESTS: 0

      - name: Test Kubernetes
        run: |
          dotnet test \
            --project tests/KubeUI.Kubernetes.Tests/KubeUI.Kubernetes.Tests.csproj \
            --configuration Release \
            --no-build \
            --hangdump \
            --hangdump-timeout 1m \
            --report-xunit-trx \
            --report-xunit-trx-filename kubernetes-test-results.trx \
            --coverage \
            --coverage-output-format cobertura \
            --coverage-output coverage-kubernetes.cobertura.xml
        env:
          KUBEUI_RUN_KIND_TESTS: 0

      - name: Upload test dump
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-diagnostics
          path: TestResults/

      - name: Test Report
        uses: dorny/test-reporter@v3
        if: (!cancelled())
        with:
          name: KubeUI Tests
          path: TestResults/*.trx
          reporter: dotnet-trx

      - name: Test Summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          check_name: KubeUI Tests
          comment_mode: always
          files: TestResults/*.trx

      - name: Coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: TestResults/coverage-avalonia.cobertura.xml,TestResults/coverage-kubernetes.cobertura.xml
          fail_ci_if_error: false
