name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100-preview9-014004  

    - name: Publish
      working-directory: src/KubeUI
      run: dotnet publish --configuration Release

    - name: Install Netlify CLI
      run: |
        $env:NPM_CONFIG_PREFIX = "~/.npm-global";
        npm install netlify-cli -g;
      shell: pwsh

    - name: Deploy to Netlify CI
      run: |       
        cd /home/runner/.npm-global/bin/
      
        $env:NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN_CI}";
        $env:NETLIFY_SITE_ID = "${NETLIFY_SITE_ID_CI}";
        $publishDir = "/home/runner/work/KubeUI/KubeUI/src/KubeUI/bin/Release/netstandard2.0/publish/KubeUI/dist/";
        
        $output = (.\netlify deploy --json -d $publishDir) | Out-String;
        
        $url = $(ConvertFrom-Json $output).deploy_url;
        Write-Host $url;
        Set-Content -Path "/home/runner/work/KubeUI/KubeUI/src/KubeUI.Tests/BrowserTestsAddress.config" -Value $url;
      shell: pwsh

    - name: Test
      working-directory: src/KubeUI.Tests
      run: dotnet test --configuration Release
