name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100-preview9-014004
    
    - name: Build
      working-directory: src/KubeUI
      run: dotnet build --configuration Release
      
    - name: Publish
      working-directory: src/KubeUI
      run: dotnet publish --configuration Release

    - name: Install Netlify CLI
      run: |
        $env:NPM_CONFIG_PREFIX = "~/.npm-global";
        npm install netlify-cli -g;
      shell: pwsh

    - name: Deploy to Netlify CI
      run: |
        $env:NETLIFY_AUTH_TOKEN = "${NETLIFY_AUTH_TOKEN_CI}";
        $env:NETLIFY_SITE_ID = "${NETLIFY_SITE_ID_CI}";
        $output = (.npm-global/bin/netlify deploy --json -d src/KubeUI/bin/Release/netstandard2.0/publish/KubeUI/dist/) | Out-String;
        $url = $(ConvertFrom-Json $output).deploy_url;
        Write-Host $url;
        Set-Content -Path "src/KubeUI.Tests/BrowserTestsAddress.config" -Value $url;
      shell: pwsh

    - name: Test
      working-directory: src/KubeUI.Tests
      run: dotnet test --configuration Release
      shell: pwsh
