name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  build-test:
    name: Build & Test
    uses: ./.github/workflows/build-test.yml

  semantic-release:
    name: Bump Version
    needs: [build-test]
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ (steps.semantic.outputs.new_release_published && steps.semantic.outputs.new_release_version) || '0.0.1-alpha.1' }}
      new_release_notes: ${{ steps.semantic.outputs.new_release_notes }}
    steps:
    - uses: actions/checkout@v7

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v6.0.0
      id: semantic
      with:
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-matrix:
    name: Publish Installers
    needs: [semantic-release]
    uses: ./.github/workflows/publish-installer.yml
    secrets: inherit
    with:
      package_version: ${{ needs.semantic-release.outputs.new_release_version }}
      release_notes: ${{ needs.semantic-release.outputs.new_release_notes }}
      download_releases: ${{ needs.semantic-release.outputs.new_release_published == 'true' }}
      enable_code_signing: true

  release:
    if: needs.semantic-release.outputs.new_release_published == 'true'
    name: Create Release
    needs: [semantic-release, publish-matrix]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        path: dist/

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v6.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
