name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  publish-docs:
    if: github.ref == 'refs/heads/main'
    name: Publish Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: current
          cache: npm
          cache-dependency-path: website/package-lock.json

      - name: Install dependencies
        working-directory: website
        run: npm ci

      - name: Build website
        working-directory: website
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: website/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e

  build-test:
    name: Build & Test
    uses: ./.github/workflows/build-test.yml

  semantic-release:
    name: Bump Version
    needs: [build-test]
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ (steps.semantic.outputs.new_release_published && steps.semantic.outputs.new_release_version) || '0.0.1-alpha.1' }}
      new_release_notes: ${{ steps.semantic.outputs.new_release_notes }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v6.0.0
      id: semantic
      with:
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-matrix:
    name: Publish Installers
    needs: [semantic-release]
    uses: ./.github/workflows/publish-installer.yml
    secrets: inherit
    with:
      package_version: ${{ needs.semantic-release.outputs.new_release_version }}
      release_notes: ${{ needs.semantic-release.outputs.new_release_notes }}
      download_releases: ${{ needs.semantic-release.outputs.new_release_published == 'true' }}
      enable_code_signing: true

  release:
    if: needs.semantic-release.outputs.new_release_published == 'true'
    name: Create Release
    needs: [semantic-release, publish-matrix]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

    - name: Download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        path: dist/

    - name: Clean Dist
      shell: pwsh
      run: |
        Remove-Item -Path dist/website -Recurse -Force

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v6.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
