name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Publish
      working-directory: src/KubeUI.Client
      run: dotnet publish --configuration Release

    - name: Deploy to Test
      id: netlify
      uses: ivanjosipovic/actions/cli@master
      with:
        args: deploy --json -d src/KubeUI.Client/bin/Release/netstandard2.1/publish/KubeUI.Client/dist/
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_CI }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_CI }}
        
    - name: Get Test Address
      run: |
        $url = $(ConvertFrom-Json '${{ steps.netlify.outputs.output }}').deploy_url;
        Write-Output $url;
      shell: pwsh