name: sync-extensions

on:
  push:
    branches:
      - alpha
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  sync-extensions:
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Clean Extensions
        shell: pwsh
        run: Remove-Item "src/KubeUI.Core/ControlExtensions.Generated/*"  -Force -Recurse

      - name: Install Tool
        run: dotnet tool install --global AvaloniaExtensionGenerator --prerelease

      - name: Run Generator
        working-directory: src/KubeUI.Core
        run: avalonia-amd-gen

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          branch: sync-extensions
          commit-message: "chore: Update Extensions"
          title: "chore: Update Extensions"
          body: "Automated Extension Sync"
